name: grabber
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

#icons
  cupertino_icons: ^1.0.8
  lottie: ^3.0.0

#text
  google_fonts: ^6.2.1

# time
  intl: ^0.20.2

#State Management
  get: ^4.6.6
  http: ^1.2.2

#firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  fluttertoast: ^8.2.10
  firebase_storage: ^12.4.0
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.1

# location
  geolocator: ^14.0.2
  geocoding: ^4.0.0

# payment
  flutter_stripe: ^11.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  
  assets:
   - Assets/Lottie/
   - Assets/Image/
   - Assets/Image/Profile/

  
  
  
  
  
  
  
  
  
